### PR TITLE
Removed unused functions

### LINKED ISSUE #261: [Question] strip down hotness/anitya.py?
I've been taking a look at the-new-hotness and it appears to me that `hotness/anitya.py` contains quite a lot of unused code?

The following methods of `Anitya` are used nowhere else in this project:
- `map_new_package`
- `update_url`
- `add_new_project`
- `get_project_by_package`
- `search_by_homepage`

which leaves only `Anitya.force_check` being actively used inside the-new-hotness or am I mistaken?

If not, how about dropping these methods?

### PR DESCRIPTION
**Pull request by pgporada**
Hi, I'm just passing by and took a stab at what looks like an easy ticket. I used [vulture](https://pypi.org/project/vulture/) and this one-liner to help find these functions.
```
cd the-new-hotness
for i in $(vulture . 2>&1 | grep 'unused function' | awk '{print $4}' | sed "s/'//g"); do grep -r ${i}; done
```

Fixes #261

### CODE REVIEW

**Comment by Zlopez** [comment]
According to the [last test run](https://jenkins-fedora-apps.apps.ci.centos.org/blue/organizations/jenkins/the-new-hotness/detail/PR-270/3/pipeline/18) this PR is introducing some new issues:
* Unused imports
* `AttributeError: module 'hotness.helpers' has no attribute 'match_interval'`

I probably missed those earlier.

**Comment by Zlopez** [comment]
Just one more thing and we are ready.

Could you squash the commits?

**Comment by Zlopez** [comment]
@pgporada I wanted to squash it by myself, but it looks like I don't have write access to your branch. Could you squash the commits and rebase to latest master?

**Comment by pgporada** [comment]
Yes sorry, this slipped my mind. Thank you for being patient and guiding me.

**Comment by Zlopez** [comment]
@pgporada Your contribution is welcome. I just need to poke CI guys, because it looks like CI is no longer catching the PR updates on the-new-hotness.

**Comment by Zlopez** [comment]
@pgporada Could you rebase this PR to latest master. I was able to finally solve the issue with CentOS CI.

**Comment by Zlopez** [comment]
I wasn't able to edit your PR and do the rebase, so I created a new one #280.

**Pull request closed without merging**
