### PR TITLE
replace YUM with DNF

### PR DESCRIPTION
**Pull request by phracek**
Signed-off-by: Petr Hracek <phracek@redhat.com>

This pull request replaces YUM with DNF.

### CODE REVIEW

**Comment by ralphbean** [comment]
We need to be able to handle both.  :(

The node we run this on in fedora infra is a RHEL7 box.

Can you make it configurable?

Have you given it a running test with the dnf tools?

**Comment by pypingou** [comment]
@phracek need help with this one?

**Comment by phracek** [comment]
Sure I will update my PR. Both should be possible.

**Comment by pypingou** [comment]
Hm, looks like this is changing more than what the title says. Shouldn't we keep those two changes separate and in two different PRs ?

**Comment by phracek** [comment]
Sure but how to do it. It was done automatically via web:(

Of course two PR are the best.

**Comment by pypingou** [comment]
Ah, you might have to use git for this, just keep the two set of changes into two different branches.

The current branch you're using for the yum/dnf change and another branch for the rebasehelper

**Comment by phracek** [comment]
ok. will do it.

**Comment by phracek** [comment]
By the way, shall I revert "rebase-helper integration" commit?

How to handle with it before I will introduce 'rebase-helper' branch.

**Comment by phracek** [comment]
I think that easiest way is to close PR.

**Pull request closed without merging**
