### PR TITLE
Retrieve the monitoring status from dist-git instead of fedora-scm-requests

### PR DESCRIPTION
**Pull request by pypingou**
Signed-off-by: Pierre-Yves Chibon <pingou@pingoured.fr>

### CODE REVIEW

**Comment by Zlopez** [comment]
:+1: Could you just solve the conflict and add entry in CHANGELOG?

**Comment by pypingou** [comment]
Adjusted :)

**Comment by pypingou** [comment]
Note this is only applicable in staging atm :)

**Comment by Zlopez** [comment]
Closes #256

**Comment by pypingou** [comment]
Wait, I missed something

**Comment by Zlopez** [comment]
I want to deploy a new version with few fixes after I will reproduce the issue in staging, this could be a nice addition. :-)

**Comment by pypingou** [comment]
It was still using yaml, now it's using json as it should :)

**Comment by Zlopez** [comment]
I rebased the branch to latest master. Tests are passing now. Do you want to add something or should I merge it?

**Comment by pypingou** [comment]
I think it should be good to go :)

**Comment by Zlopez** [comment]
Closes #233

**Pull request merged**
