### PR TITLE
PR  which supports YUM and DNF usage

### PR DESCRIPTION
**Pull request by phracek**
This Pull Request supports as YUM as DNF.

It includes also SPEC and setup.py modifications.

### CODE REVIEW

**Comment by ralphbean** [comment]
Cool.  So, this expects to find a new section in ``/etc/os-release`` specifically for the-new-hotness?

.. and if that section is not present, it defaults to ``yum``, correct?

**Comment by ralphbean** [comment]
Hm, would it be easier to just check for the existence of ``/usr/bin/dnf`` and use that if it is present, otherwise use ``/usr/bin/yum``?

**Comment by pypingou** [comment]
I was wondering about just providing the command to run in the configuration file, something like:
``cmd='/usr/bin/repoquery'`` vs ``cmd=/usr/bin/dnf repoquery`` since the rest of the command is the same.

**Comment by phracek** [comment]
@pypingou ```cmd='/usr/bin/repoquery'``` doesn't work with DNF.

But it could be simplified. Sure.

And of course check for ```/usr/bin/dnf``` is much simpler then parsing /etc/os-release. EPEL7 uses YUM and F22-> uses dnf.

**Comment by pypingou** [comment]
> @pypingou cmd='/usr/bin/repoquery' doesn't work with DNF.

I agree, but if you set the command in the configuration file it's easy to switch a variable to another:
from ``cmd = '/usr/bin/repoquery'`` to ``cmd = '/usr/bin/dnf repoquer``

**Comment by phracek** [comment]
You are right.

**Comment by phracek** [comment]
What configuration file shall I use? I don't see it.

**Comment by ralphbean** [comment]
How about [this one](https://github.com/fedora-infra/the-new-hotness/blob/develop/fedmsg.d/hotness-example.py)?

**Comment by ralphbean** [comment]
It gets loaded as ``self.config`` [here](https://github.com/fedora-infra/the-new-hotness/blob/develop/hotness/consumers.py#L81).

**Comment by phracek** [comment]
Ok, I will update PR. Thanks

**Comment by phracek** [comment]
Unfortunately on my F23 I see following:

~~~
unused-4-101: ~$ ls -la /usr/bin/{yum,dnf}
lrwxrwxrwx. 1 root root    5 Nov 27 11:25 /usr/bin/dnf -> dnf-3
-rwxr-xr-x. 1 root root 1447 Nov 16 15:59 /usr/bin/yum
unused-4-101: ~$ 
~~~

Therefore I guess that detection of binary is not enough.

**Comment by phracek** [comment]
But the whole functionality, like use dnf or yum, can be moved to config.

**Comment by pypingou** [comment]
> But the whole functionality, like use dnf or yum, can be moved to config.

Might be just as easy :)

**Comment by ralphbean** [comment]
Any luck moving this to the [config](https://github.com/fedora-infra/the-new-hotness/blob/develop/fedmsg.d/hotness-example.py)?  Values added there become available as ``self.config`` [here](https://github.com/fedora-infra/the-new-hotness/blob/develop/hotness/consumers.py#L81).

**Comment by phracek** [comment]
Sorry guys, I was a pretty busy. I plan to do it Wednesday or Thursday.

**Comment by ralphbean** [comment]
No rush -- just trying to keep communication channels open.  :)

**Comment by ralphbean** [comment]
I think this is handled elsewhere now (in the rebase-helper PR).

**Pull request closed without merging**
